import { createFileRoute, Link, useNavigate } from '@tanstack/react-router';
import { toast } from 'sonner';
import { AppShell } from '@/components/app-shell';
import { CustomerDialog } from '@/components/customer-dialog';
import { Button } from '@/components/ui/button';
import { customerBalance, customersApi, invoicesApi, jobsApi, paymentsApi } from '@/lib/db';
import { formatINR } from '@/lib/invoice-calc';
import { pageMeta } from '@/lib/page-meta';
export const Route=createFileRoute('/customers/$id')({head:()=>pageMeta('Customer ledger','Customer details, invoices, jobs and payment history.'),component:CustomerDetail});
function CustomerDetail(){const {id}=Route.useParams();const customer=customersApi.useOne(id);const invoices=invoicesApi.useList();const payments=paymentsApi.useList();const jobs=jobsApi.useList();const update=customersApi.useUpdate();const remove=customersApi.useRemove();const navigate=useNavigate();const c=customer.data;const queries=[customer,invoices,payments,jobs];
 if(queries.some(q=>q.isLoading))return <AppShell title="Customer"><p>Loading…</p></AppShell>;
 if(queries.some(q=>q.error))return <AppShell title="Customer"><p role="alert">Unable to load customer history.</p></AppShell>;
 if(!c)return <AppShell title="Customer"><p>Customer not found.</p></AppShell>;
 const ci=invoices.data?.filter(i=>i.customerId===id)??[];const cp=payments.data?.filter(p=>p.customerId===id)??[];const cj=jobs.data?.filter(j=>j.customerId===id)??[];const balance=customerBalance(id,ci,cp);
 return <AppShell title={c.name} actions={<CustomerDialog initial={c} trigger={<Button size="sm" variant="outline">Edit</Button>} onSave={data=>update.mutate({id,data},{onSuccess:()=>toast.success('Customer saved'),onError:e=>toast.error(e.message)})}/>}><p>{c.address}</p><p className="text-sm text-muted-foreground">{c.state} · {c.gstin||'No GSTIN'}</p><p className="mt-2 text-sm">{c.phone} {c.email}</p><div className="my-6 grid gap-4 sm:grid-cols-3">{[['Invoiced',balance.invoiced],['Received',balance.received],['Balance due',balance.balance]].map(([label,value])=><div key={label} className="rounded-lg border bg-card p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl tnum">₹{formatINR(Number(value))}</p></div>)}</div><h2 className="mt-8 text-lg font-semibold">Invoices</h2>{ci.length?ci.map(i=><Link to="/invoices/$id" params={{id:i.id}} key={i.id} className="flex justify-between gap-4 border-b py-4"><span>{i.invoiceNo} · {i.invoiceDate} · {i.status}</span><span className="tnum">₹{formatINR(i.totalAmount)}</span></Link>):<p className="py-4 text-muted-foreground">No invoices.</p>}<h2 className="mt-8 text-lg font-semibold">Payment history</h2>{cp.length?cp.map(p=><div key={p.id} className="flex justify-between border-b py-4"><span>{p.date} · {p.type}</span><span>₹{formatINR(p.amount)}</span></div>):<p className="py-4 text-muted-foreground">No payments recorded.</p>}<h2 className="mt-8 text-lg font-semibold">Jobs</h2>{cj.map(j=><p key={j.id} className="border-b py-4">{j.description} · {j.status}</p>)}{!cj.length&&<p className="py-4 text-muted-foreground">No jobs.</p>}<Button className="mt-8" variant="destructive" disabled={!!(ci.length||cp.length||cj.length)||remove.isPending} onClick={()=>{if(confirm('Delete this customer?'))remove.mutate(id,{onSuccess:()=>navigate({to:'/customers'}),onError:e=>toast.error(e.message)});}}>Delete customer</Button>{!!(ci.length||cp.length||cj.length)&&<p className="mt-2 text-xs text-muted-foreground">Customers with existing records cannot be deleted.</p>}</AppShell>;
}
